affinity: {}
cainjector:
  affinity: {}
  deploymentAnnotations: {}
  enabled: true
  extraArgs: []
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/jetstack/cert-manager-cainjector
    tag: cert-manager-cainjector-1.6.12-am2
  nodeSelector: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  strategy: {}
  tolerations: []
clusterResourceNamespace: ""
deploymentAnnotations: {}
extraArgs: []
extraEnv: []
global:
  imagePullSecrets: []
  leaderElection:
    namespace: kube-system
  logLevel: 2
  podSecurityPolicy:
    enabled: false
    useAppArmor: true
  priorityClassName: ""
  rbac:
    create: true
image:
  pullPolicy: IfNotPresent
  repository: quay.io/jetstack/cert-manager-controller
  tag: cert-manager-controller-1.6.12-am2
ingressShim: {}
nodeSelector: {}
podAnnotations: {}
podLabels: {}
prometheus:
  enabled: true
  servicemonitor:
    enabled: false
    interval: 60s
    labels: {}
    path: /metrics
    prometheusInstance: default
    scrapeTimeout: 30s
    targetPort: 9402
replicaCount: 1
resources: {}
securityContext: {}
serviceAccount:
  annotations: {}
  create: true
  name: null
strategy: {}
tolerations: []
volumeMounts: []
volumes: []
webhook:
  affinity: {}
  deploymentAnnotations: {}
  extraArgs: []
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/jetstack/cert-manager-webhook
    tag: cert-manager-webhook-1.6.12-am2
  injectAPIServerCA: true
  nodeSelector: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  securePort: 10250
  securityContext: {}
  serviceName: cert-manager-webhook
  strategy: {}
  tolerations: []
