apiVersion: v1
description: A Helm chart for managing Aspen Mesh metrics-collector
name: aspen-mesh-metrics-collector
version: 1.6.12-am2
appVersion: 1.6.12-am2
tillerVersion: ">=2.7.2"
keywords:
  - istio
  - aspenmesh
  - metrics
engine: gotpl
icon: https://aspenmesh.io/wp-content/uploads/2018/06/favicon-192.png
