apiVersion: v1
kind: Secret
metadata:
  name: aspen-mesh-pull-secret
  namespace: istio-system
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJZWE53Wlc1dFpYTm9LM1Z6WlhKelgzSmxiR1ZoYzJWZk1WOHhYM0IxYkd3NlRFVmFORGxMVVVaQldrdFlUa3BPUTFkVU9FNWFOa0pWVGs0M1V6QXlOamxNVkUxRFZUSktVVlJLUTFOU1NsUldVMEZEVEZFM1Z6bERNRVZFTURZMFNBPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
