apiVersion: v1
kind: ConfigMap
metadata:
  name: aspen-mesh-controlplane-configurator
  namespace: {{ .Release.Namespace }}
  labels:
    app: aspen-mesh-controlplane
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  run.sh: |-
{{ .Files.Get "create-webhook-certs.sh" | indent 4 }}
  webhook.yaml: |-
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: aspen-mesh-controlplane
      namespace: {{ .Release.Namespace }}
      labels:
        app: aspen-mesh-controlplane
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      ownerReferences:
      - apiVersion: v1
        blockOwnerDeletion: false
        controller: false
        kind: Service
        name: aspen-mesh-controlplane
        uid: __UID__
    webhooks:
    - name: availability-class.aspenmesh.io
      clientConfig:
        service:
          name: aspen-mesh-controlplane
          namespace: {{ .Release.Namespace }}
          path: "/validate"
          port: {{ template "aspen-mesh-controlplane.validationPort" .}}
        caBundle: __CABUNDLE__
      rules:
      - apiGroups: ["policy.aspenmesh.io"]
        apiVersions: ["v1alpha1"]
        resources: ["availabilityclasses", "availabilityclassattachments"]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
      failurePolicy: Fail
      sideEffects: None
      admissionReviewVersions: ["v1beta1"]

